env:
    token: "ENCRYPTED[de78fc223d92eedcbc2deb1a07ff58c47653794edb7e89bed9c375108b68f7bb59db7b2ad3b4eb4fbb048e555976c446]"
    chat_id: "ENCRYPTED[7c060fdbbe868a7529d8743a2d8d59f1386b7793b0d66dd84bb33d116dceb19c340510e106dea90d793fed43294158a6]"
    
task:
  name: "Kernel deploy.."
  timeout_in: 2h
  container:
      image: panchajanya1999/archlinux:latest
      cpu: 8
      memory: 32G

  Build_script:
      - git clone --depth=1 -b oldcam-hmp https://github.com/ZenitsuID/kernel_xiaomi_lavender lv && cd lv
      - bash build.sh --azure
